### ISSUE TITLE
关于gtest的问题

### ISSUE THREAD

**Issue by KANG-1998** [PCNL-EDA/iEDA-standard-develop#14]
1、gtest的测试宏TEST(),TEST_F()书写的位置，一定要在main函数所在的源文件吗？
2、测试完毕后，main(){ 
                                        ::testing::InitGoogleTest(&argc, argv); 
                                        return RUN_ALL_TESTS();
                            }
main函数中关于gtest的内容要怎么处理？删掉?

**Comment by simintao** [comment]
main函数不是必须的，没有特殊要处理的，可以不写main函数，TEST(),TEST_F()书写位置可以在test文件夹任何一个文件中，但不要在正常设计代码里面
