### ISSUE TITLE
关于文档生成工具Doxygen问题

### ISSUE THREAD

**Issue by KANG-1998** [PCNL-EDA/iEDA-standard-develop#16]
对项目添加doxygen类型的注释（包括类、函数的注释）后，用doxygen工具生成项目文档，其中对类的注释可以生成关于类的内容介绍，但是文档里没有关于函数内容介绍（我用的是@fn function-name对函数添加的注释）

**Comment by simintao** [comment]
这个不清楚，也可能是doxygen的bug，你找手册确认下
