### ISSUE TITLE
关于Doxygen注释风格与cpplint工具的问题

### ISSUE THREAD

**Issue by zongbaoi** [PCNL-EDA/iEDA-standard-develop#17]
我之前按照Doxygen风格加的版权信息注释，如下：

/**

 *@file

 *@author  <作者>

 *@date         <创建日期>

 *@version <版本号>

 *

 *@section LICENSE

 *

 *<文件说明>

 */

但是cpplint工具会报：“No copyright message found.”的警告。
难道是cpplint里设置的google风格的版权注释和Doxygen风格的规则不一样吗？

**Comment by simintao** [comment]
另外还需要增加  @copyright Copyright (c) 2021 PCL IEDA

**Comment by simintao** [comment]
可以使用VSCode插件DoxyGen自动生成
