### ISSUE TITLE
google test的使用

### ISSUE THREAD

**Issue by shengkunwu** [PCNL-EDA/iEDA-standard-develop#18]
自己写的函数是和图有关的函数。包括：用矩阵生成一个图函数，求每点到起点的距离，打印路径函数。

自己在调试的时候，学了google test的语法，但是发现可以用EXPECT_EQ去测试求距离函数。但是生成一个图的函数是一个构造函数，好像单纯用googletest的语法不能测试，所以自己又写了一个打印图的函数，然后再写一个自己的测试函数去检查自己的生成图的函数。这一部分就没有用google test. 打印路径函数的返回值是void,所以这种函数我不知道怎么用google test去测试。

**Comment by simintao** [comment]
生成一个图的函数你可以自己写构造，也可以用GoogleTest带的另外一个工具GMock生成，你可以了解下GMock看是否能产生你所需要的，打印路径函数返回值你设置成void，这说明你程序设计时没有考虑程序的可测试性，你可以输出路径到一个数据结构中，或者其他形式能让测试人员观察到你想测试的东西。
