### ISSUE TITLE
git pull

### ISSUE THREAD

**Issue by shengkunwu** [PCNL-EDA/iEDA-standard-develop#21]
文档中写了需要git pull。
原本顺序是，git clone, git branch, git checkout, git add, git commit, git push.
那么git pull这个命令最合理的应该在谁之前？

**Comment by Xingquan-Li** [comment]
git pull是把代码从github的远程下载更新到本地的命令；

在用git pull之前，说明你已经把代码git push到github远程，然后每次想要git push之前，你要把代码git pull一下（防止别人有git push新的代码到你的仓库）。如果确定这个仓库只有你一个人管理和维护，那就不一定要git pull，每次git push就好
