### ISSUE TITLE
关于缺失main函数的程序问题

### ISSUE THREAD

**Issue by KANG-1998** [PCNL-EDA/iEDA-standard-develop#25]
老师，在分析曾智圣的项目代码过程中，发现生成的可执行程序在没有主函数的情况下依然可以照常执行，没有主函数，程序的入口在哪？

**Comment by simintao** [comment]
请提issue的时候，把相关代码截图发上来，这样后期的同学不用去找代码看，另外请确认是没有主程序还是没有找到，你是怎么得出这个结论得。还有一个简单的办法就是debug得时候通过调用栈看主函数在哪里。
