### ISSUE TITLE
算法问题

### ISSUE THREAD

**Issue by shengkunwu** [PCNL-EDA/iEDA-standard-develop#30]
关于A星算法，在做这个训练的过程中我仔细地思考了A星算法，我尝试去证明A星算法求出的路径是最短的，但是发现好像其找到的路径未必的最短路径。我还没构造反例，所以我想问问能否有例子说明A星算法求出的未必最短或者证明其求出的是最短的。

我的代码其实是我自己尝试的一个逐层求距离然后反向搜索的算法。当然我也无法证明我这个算法能求出最短路径。

**Comment by simintao** [comment]
A*算法是dijkstra算法的变种，如果启发式函数选择的不合理可能找到的不是最短路径，启发式函数为0则是dijkstra算法，网上应该有很多资料，可以了解下。

**Comment by simintao** [comment]
https://zh.wikipedia.org/wiki/A*%E6%90%9C%E5%B0%8B%E6%BC%94%E7%AE%97%E6%B3%95
