### ISSUE TITLE
指针和引用对齐格式

### ISSUE THREAD

**Issue by harryustc** [PCNL-EDA/iEDA-standard-develop#43]
![image](https://user-images.githubusercontent.com/68261483/131467835-dacaf840-8910-4afd-9b1a-65b0ec451b44.png)

google规范（如上图）中并无明确规定指针和引用的对齐格式，请老师明确本项目中指针和引用的对齐格式

**Comment by simintao** [comment]
一行只声明一个变量，至于靠左还是靠右看个人风格，后面我们会统一用clang-format
