### ISSUE TITLE
标准培训建议

### ISSUE THREAD

**Issue by harryustc** [PCNL-EDA/iEDA-standard-develop#44]
明确使用的具体工具及配置文件，比如统一使用clang-format并加载相同的.clang-format配置文件。
我在浏览iEDA代码仓库时，发现里面的代码格式并不统一，一些配置文件的内容也各不相同。
可能这种情况的出现是历史原因，所以我希望能在标准开发培训时就统一使用相同的工具及配置文件，并对这些工具进行针对性学习。专门安排时间进行工具的使用和学习，也有助于大家一起交流问题。

**Comment by simintao** [comment]
对于工具的培训是有的，请参考语雀资料https://ieda.yuque.com/g/kzqyb5/kbqu52/folder/19873560
