### ISSUE TITLE
关于代码规范不一的问题

### ISSUE THREAD

**Issue by YihangQiu** [PCNL-EDA/iEDA-standard-develop#49]
利用clang-format插件按照Google风格对代码格式化后的效果，与 "C++标准化开发.ppt“要求的规范，有一些出入。
例如：
ppt要求限定符前要空一格，但是clang-format格式化后的代码没有空一格；头文件包含的次序也有差异。
我们应该依据哪个规范呢？是直接依据clang-format后的效果呢，还是需要对clang-format后的代码规范进行微调呢？

**Comment by simintao** [comment]
水滴训练只要保证所有代码是一致的有用clang-format就可以，项目代码会统一格式化。
