### ISSUE TITLE
关于成员变量赋值的问题

### ISSUE THREAD

**Issue by jerry9055** [PCNL-EDA/iEDA-standard-develop#52]
![image](https://user-images.githubusercontent.com/85446108/132305903-9cac7dcf-628f-47a9-86ce-33720f2baa2b.png)

如图，在给对象的成员变量赋值的时候，我可以做到 链式编程 person.set1(x1).set2(x2)...
但是这样经过 clang-fomat之后就变得不太好看。
如果只赋值，不返回对象引用，那以后修改就需要多几行
问题1：给简单成员变量赋值的时候，**建议返回 void 还是 返回 *this 呢？**

**Comment by simintao** [comment]
建议void
