### ISSUE TITLE
编程规范与实践冲突

### ISSUE THREAD

**Issue by harryustc** [PCNL-EDA/iEDA-standard-develop#53]
在语雀文档的[编程规范](https://ieda.yuque.com/kzqyb5/ehhi05/1210138)中，类声明顺序如下所示
![image](https://user-images.githubusercontent.com/68261483/132318477-54fbd5b2-a2c8-4b36-82e3-4192199f7c71.png)
@KANG-1998 在进行 code review 时依照 iEDA 的开发实践，建议将声明顺序改为：构造函数(包括复制构造，移动构造)，析构函数，operator重载，get方法，set方法，其它函数。
请问 @simintao 老师，是否需要对[编程规范](https://ieda.yuque.com/kzqyb5/ehhi05/1210138)进行修改？

**Comment by simintao** [comment]
可以的，请直接修改下

**Comment by harryustc** [comment]
> 可以的，请直接修改下

已经修改
![image](https://user-images.githubusercontent.com/68261483/132342798-f25a80eb-d550-43ca-a865-1ca6acef5187.png)

**Comment by simintao** [comment]
好的
